### ISSUE TITLE
plugin not working for me

### ISSUE THREAD

**Issue by mcondarelli** [GEROMAX/redmine_diff_popup#2]
I installed plugin and it dutifully displays the `(diff)` link in a test issue whose Description I modified.
Unfortunately clicking it does not show anything.
Also standard log `.../redmine/log/production.log` does not show any activity.
I already checked pop-ups are enabled in my browser (Firefox).
What am I missing?

**Comment by GEROMAX** [comment]
Hi @mcondarelli .

Has error occurred?
Please make sure popup is enabled by user preference.

**Comment by mcondarelli** [comment]
Hi GEROMAX,
I can see no error, where should I look?
I also see no "pop-up enabling" in Redmine (in Browser they *are* enabled).
Can Yo be a bit more specific?
TiA!

**Comment by GEROMAX** [comment]
Hi @mcondarelli .

User Preference has are this link.
<img width="171" alt="myaccount" src="https://user-images.githubusercontent.com/22927460/31580455-36f6be66-b18b-11e7-8964-2544a729e8b0.png">

Popup setting is here.
<img width="367" alt="userpreference" src="https://user-images.githubusercontent.com/22927460/31580460-5144ac92-b18b-11e7-8743-37a79c579818.png">

And I Confirmed working in FireFox 56.0.1.

**Comment by mcondarelli** [comment]
Hi @GEROMAX,
I hadn't spotted that, but it's dutifully checked.

![image](https://user-images.githubusercontent.com/870849/31583265-261e8094-b198-11e7-8081-6b2815240b6d.png)

Actually I can see (looking real good) a printout "Loading" flashing very briefly on screen when I click "(diff)" link.
It is  located a bit below where the "% Done:" is in ".../issues/##" page (if it matters).

I did some digging and I discovered this Firefox security error:

    Blocked loading mixed active content “http://redmine/diff_popup/journal_diff?detail_id=1&id=1&indice=1”[Learn More]  jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4:25546

The [Learn More](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default) link does seem to indicate this is a "web developer error" and *should* be blocked.

Disabling the check (*if* I find how to do that) just to have diff working doesn't seem a very good idea.

**Note:** I get the same results with a recent Chromium browser.
I am testing with: 
- Firefox 56.0 (64-bit)
- Chromium Version 61.0.3163.100 (Developer Build) built on Debian 9.1, running on Debian 9.2 (64-bit)

**Comment by GEROMAX** [comment]
Hi @mcondarelli .

Probably I understood the cause.
This plugin cannot support "https" now maybe.

I try resolve this problem.
But it will take a little time.(not have https server now..)

Thank you for detail report.

**Comment by GEROMAX** [comment]
Hi @mcondarelli .

I tested this plugin on https server.
But I cannot found your problem.
The URL of ".../redmine/diff_popup/journal_diff?" has been converted from http to https.

Please make sure that all pages of redmine are set to https on your server.

Thanks.

**Comment by GEROMAX** [comment]
Hi @mcondarelli .

I tested on real proven https server, but not found it problem.
It is work properly.

If you have problem yet, please report issue again.
