### ISSUE TITLE
Any "old" version to be used for Redmine 3.2.x

### ISSUE THREAD

**Issue by mauriziotallarico** [GEROMAX/redmine_diff_popup#3]
Hello,
is there any release working with 3.2.x even if not "state of the art" ?

Thanks a lot.

**Comment by GEROMAX** [comment]
Hi @mauriziotallarico .

I tested 'master'(tag:1.0.0) of this plugin on Redmine 3.2.2 by chance just now.
And it was no problem in my environment.

It work for you too maybe.

Thanks.

**Comment by GEROMAX** [comment]
Hi @mauriziotallarico .

Add support Redmine 3.2.2 in plugin ver 1.0.0 and 1.0.1.

If you have other problem, please report issue.
